server {

    listen 80;
    server_name localhost;

    include /etc/nginx/security.conf;
    include /etc/nginx/gzip.conf;
    include /etc/nginx/proxy.conf;

    location / {

        root /usr/share/nginx/html;
        index index.html;

    }

    location /health {

        add_header Content-Type text/plain;
        return 200 "Healthy";

    }

}