name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config